apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-config
  namespace: yelp-lab2
data:
  MONGO_URI: mongodb://mongodb.yelp-lab2.svc.cluster.local:27017
  MONGO_DB_NAME: yelp_lab2
  KAFKA_BOOTSTRAP_SERVERS: kafka.yelp-lab2.svc.cluster.local:9092
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-secrets
  namespace: yelp-lab2
type: Opaque
stringData:
  SECRET_KEY: supersecretkey